# Generated by Django 6.0.6 on 2026-06-29 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProgressReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("chest", models.DecimalField(decimal_places=2, max_digits=5)),
                ("waist", models.DecimalField(decimal_places=2, max_digits=5)),
                ("hips", models.DecimalField(decimal_places=2, max_digits=5)),
                ("arm", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="fitness.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
